image: ${CI_REGISTRY}/utilities/build-images/ubuntu-18-04-build:master
stages:
  - deploy

# jobs:

deploy:toGithub:
  stage: deploy
  when: manual
  only:
    - branches
  tags:
    - docker
  environment:
    name: github
    url: https://github.com/SoftingIndustrial/datafeed-edge-connector
  script:
    - git lfs fetch --all
    - git remote add public https://oauth2:${OAUTH2TOKEN}@github.com/SoftingIndustrial/datafeed-edge-connector.git
    - git push public HEAD:refs/heads/${CI_COMMIT_REF_NAME}
  after_script:
    - git remote remove public
